language: python
python:
    - "3.4"
    - "3.5"
install:
    - pip install -r requirements/development.txt
script:
    - pep8 .
    - python fastube/manage.py test users posts
notifications:
    slack: hans-hq:4900EEKHsrKKOmP5UgAjS0e8
